version: v0.0.1
download_urls:
  - https://github.com/1tn1c0/mouse-sensitivity-matcher/releases
donate_url: https://donate.jw.org/ui/F/donate-home.html#/donate
startup:
  title: Information
  content: |
    <div className="card border-primary m-3">
      Cette application est entiÃ¨rement gratuite
      <li>
          Pas de compte
      </li>
      <li>
          Pas d'abonnement
      </li>
      <li>
          Donner quand vous voulez et si vous le pouvez
      </li>
      <p align="center">ğŸ˜</p>
    </div>
    <div className="card border-primary m-3">
        Nous pouvons mettre beaucoup plus
        d'options. N'hÃ©sitez pas a m'offrir un cafÃ©
        afin que je reste bien rÃ©veillÃ©  pour
        dÃ©velopper cette aplication ğŸ˜Š
    </div>