version: v0.2.1
download_urls:
  - https://github.com/1tn1c0/mouse-sensitivity-matcher/releases
donate_url: https://donate.jw.org/ui/F/donate-home.html#/donate
startup:
  title: Information
  content: |
    <legend align="center">Bienvenue !!</legend>
    <table>
      <thead>
          <tr>
            <th colspan="2"></th>
          </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <div className="card border-primary m-4">
              <div>
                Cette application est enti√®rement gratuite
                <li>Pas de compte</li>
                <li>Pas d'abonnement</li>
                <li>Donner quand vous voulez <br>et si vous le pouvez.</li>
                <p align="center">üòç</p>
              </div>
            </div>
          </td>
          <td>
            <div className="card border-primary m-3">
              Nous pouvons mettre beaucoup plus <br>
              d'options. N'h√©sitez pas a m'offrir <br>
              un caf√© afin que je reste bien <br>
              r√©veill√© pour d√©velopper cette <br>
              application üòä.
            </div>
          </td>
        </tr>
      </tbody>
    </table>