version: v0.1.0
download_urls:
  - https://github.com/1tn1c0/mouse-sensitivity-matcher/releases
donate_url: https://donate.jw.org/ui/F/donate-home.html#/donate
startup:
  title: Information
  content: |
    <div className="modal modal-content modal-dialog-centered">
      <legend align="center">Bienvenue !!</legend>
      <table>
            <thead>
                <tr>
                    <th colspan="2"></th>
                </tr>
            </thead>
        <tbody>
        <tr>
          <td>
            <div className="card border-primary m-4">
              <div>
                Cette application est enti√®rement gratuite
                <li>Pas de compte</li>
                <li>Pas d'abonnement</li>
                <li>Donner quand vous voulez et si vous le pouvez</li>
                <p align="center">üòç</p>
              </div>
            </div>
            <div className="row">
              <div className="col-md-8"></div>
              <div className="col-md-4"></div>
            </div>
          </td>
          <td>
            <div className="card border-primary m-3">
              Nous pouvons mettre beaucoup plus d'options. N'h√©sitez pas a m'offrir
              un caf√© afin que je reste bien r√©veill√© pour d√©velopper cette
              aplication üòä
            </div>
          </td>
        </tr>
        </tbody>
      </table>
    </div>